"""init

Revision ID: 3872ce5a9ec3
Revises: 
Create Date: 2021-10-01 19:05:31.056978

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3872ce5a9ec3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    op.create_index(op.f('ix_currencies_name'), 'currencies', ['name'], unique=False)
    op.create_index(op.f('ix_currencies_slug'), 'currencies', ['slug'], unique=False)
    op.create_index(op.f('ix_currencies_symbol'), 'currencies', ['symbol'], unique=False)
    op.create_table('currencyrates',
    sa.Column('currency', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('actual_date', sa.DateTime(), nullable=False),
    sa.Column('price_usd', sa.Numeric(), nullable=False),
    sa.Column('percent_change_1h', sa.Float(), nullable=False),
    sa.Column('percent_change_24h', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencyrates_actual_date'), 'currencyrates', ['actual_date'], unique=False)
    op.create_index(op.f('ix_currencyrates_currency'), 'currencyrates', ['currency'], unique=False)
    op.create_index(op.f('ix_currencyrates_date_added'), 'currencyrates', ['date_added'], unique=False)
    op.create_index(op.f('ix_currencyrates_id'), 'currencyrates', ['id'], unique=False)
    op.create_index(op.f('ix_currencyrates_percent_change_1h'), 'currencyrates', ['percent_change_1h'], unique=False)
    op.create_index(op.f('ix_currencyrates_percent_change_24h'), 'currencyrates', ['percent_change_24h'], unique=False)
    op.create_index(op.f('ix_currencyrates_price_usd'), 'currencyrates', ['price_usd'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currencyrates_price_usd'), table_name='currencyrates')
    op.drop_index(op.f('ix_currencyrates_percent_change_24h'), table_name='currencyrates')
    op.drop_index(op.f('ix_currencyrates_percent_change_1h'), table_name='currencyrates')
    op.drop_index(op.f('ix_currencyrates_id'), table_name='currencyrates')
    op.drop_index(op.f('ix_currencyrates_date_added'), table_name='currencyrates')
    op.drop_index(op.f('ix_currencyrates_currency'), table_name='currencyrates')
    op.drop_index(op.f('ix_currencyrates_actual_date'), table_name='currencyrates')
    op.drop_table('currencyrates')
    op.drop_index(op.f('ix_currencies_symbol'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_slug'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_name'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.drop_table('currencies')
    # ### end Alembic commands ###
