"""init

Revision ID: c1e9e3f46ff1
Revises: 
Create Date: 2021-10-13 13:44:04.720579

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c1e9e3f46ff1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_id'), 'currency', ['id'], unique=False)
    op.create_index(op.f('ix_currency_name'), 'currency', ['name'], unique=False)
    op.create_index(op.f('ix_currency_slug'), 'currency', ['slug'], unique=False)
    op.create_index(op.f('ix_currency_symbol'), 'currency', ['symbol'], unique=False)
    op.create_table('currencyrate',
    sa.Column('currency', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('actual_date', sa.DateTime(), nullable=False),
    sa.Column('price_usd', sa.Numeric(), nullable=False),
    sa.Column('percent_change_1h', sa.Float(), nullable=False),
    sa.Column('percent_change_24h', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencyrate_actual_date'), 'currencyrate', ['actual_date'], unique=False)
    op.create_index(op.f('ix_currencyrate_currency'), 'currencyrate', ['currency'], unique=False)
    op.create_index(op.f('ix_currencyrate_date_added'), 'currencyrate', ['date_added'], unique=False)
    op.create_index(op.f('ix_currencyrate_id'), 'currencyrate', ['id'], unique=False)
    op.create_index(op.f('ix_currencyrate_percent_change_1h'), 'currencyrate', ['percent_change_1h'], unique=False)
    op.create_index(op.f('ix_currencyrate_percent_change_24h'), 'currencyrate', ['percent_change_24h'], unique=False)
    op.create_index(op.f('ix_currencyrate_price_usd'), 'currencyrate', ['price_usd'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currencyrate_price_usd'), table_name='currencyrate')
    op.drop_index(op.f('ix_currencyrate_percent_change_24h'), table_name='currencyrate')
    op.drop_index(op.f('ix_currencyrate_percent_change_1h'), table_name='currencyrate')
    op.drop_index(op.f('ix_currencyrate_id'), table_name='currencyrate')
    op.drop_index(op.f('ix_currencyrate_date_added'), table_name='currencyrate')
    op.drop_index(op.f('ix_currencyrate_currency'), table_name='currencyrate')
    op.drop_index(op.f('ix_currencyrate_actual_date'), table_name='currencyrate')
    op.drop_table('currencyrate')
    op.drop_index(op.f('ix_currency_symbol'), table_name='currency')
    op.drop_index(op.f('ix_currency_slug'), table_name='currency')
    op.drop_index(op.f('ix_currency_name'), table_name='currency')
    op.drop_index(op.f('ix_currency_id'), table_name='currency')
    op.drop_table('currency')
    # ### end Alembic commands ###
